services:
  db:
    image: postgres:15
    env_file: 
      - .env

  app:
    image: pavelsergeev/kittens-store:${IMAGE_TAG:-latest}
    # build:
    #   context: ../.
    #   dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "1234:1234"
    env_file: 
      - .env
